files:
  "/etc/nginx/conf.d/my_custom_nginx.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      server {
        listen 80;
        server_name eplstats.eu-north-1.elasticbeanstalk.com;

        location / {
          proxy_pass http://127.0.0.1:8080; 
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

      }
